export const SPIDERLIST_SUCCESS = "SPIDERLIST_SUCCESS";
export const SPIDERLIST_FAILED = "SPIDERLIST_FAILED";
export const SPIDERLIST_FETCHING = "SPIDERLIST_FETCHING";

export const FAMILY_SUCCESS = "FAMILY_SUCCESS";
export const FAMILY_FAILED = "FAMILY_FAILED";
export const FAMILY_FETCHING = "FAMILY_FETCHING";

export const GENUS_SUCCESS = "GENUS_SUCCESS";
export const GENUS_FAILED = "GENUS_FAILED";
export const GENUS_FETCHING = "GENUS_FETCHING";

export const SPECIES_SUCCESS = "SPECIES_SUCCESS";
export const SPECIES_FAILED = "SPECIES_FAILED";
export const SPECIES_FETCHING = "SPECIES_FETCHING";

export const PROVINCE_SUCCESS = "PROVINCE_SUCCESS";
export const PROVINCE_FAILED = "PROVINCE_FAILED";
export const PROVINCE_FETCHING = "PROVINCE_FETCHING";

export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS";
export const DISTRICT_FAILED = "DISTRICT_FAILED";
export const DISTRICT_FETCHING = "DISTRICT_FETCHING";

export const DETAIL_SUCCESS = "DETAIL_SUCCESS";
export const DETAIL_FAILED = "DETAIL_FAILED";
export const DETAIL_FETCHING = "DETAIL_FETCHING";

export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const LOCATION_FAILED = "LOCATION_FAILED";
export const LOCATION_FETCHING = "LOCATION_FETCHING";

export const ADDRESS_SUCCESS = "ADDRESS_SUCCESS";
export const ADDRESS_FAILED = "ADDRESS_FAILED";
export const ADDRESS_FETCHING = "ADDRESS_FETCHING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
