export const SPIDERLIST_SUCCESS = "SPIDERLIST_SUCCESS";
export const SPIDERLIST_FAILED = "SPIDERLIST_FAILED";
export const SPIDERLIST_FETCHING = "SPIDERLIST_FETCHING";

export const FAMILY_SUCCESS = "FAMILY_SUCCESS";
export const FAMILY_FAILED = "FAMILY_FAILED";
export const FAMILY_FETCHING = "FAMILY_FETCHING";

export const GENUS_SUCCESS = "GENUS_SUCCESS";
export const GENUS_FAILED = "GENUS_FAILED";
export const GENUS_FETCHING = "GENUS_FETCHING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
