export const DETAIL_SUCCESS = "DETAIL_SUCCESS";
export const DETAIL_FAILED = "DETAIL_FAILED";
export const DETAIL_FETCHING = "DETAIL_FETCHING";

export const SPIDERLIST_SUCCESS = "SPIDERLIST_SUCCESS";
export const SPIDERLIST_FAILED = "SPIDERLIST_FAILED";
export const SPIDERLIST_FETCHING = "SPIDERLIST_FETCHING";
